name: "Build-And-Test-Variant-Reuse-Case"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

jobs:  
  app-advance-variant-windows:
    name: "Advance Variant (Windows) Reuse"
    runs-on: windows-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v2.1.1

      - name: 🟢 Install Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 18
          scope: '@naveed235812'
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Build, Test and Package
        uses: naveedkhan8067/PLE_DevOps/.github/templates/build/@main
        with:
          COMPONENT: app-advance
          VARIANT_TYPE: windows
          WORKING-DIR: ./
