name: "release-app-advance"

on:
  workflow_run:
    workflows: [Build-And-Test-Advance-App]
    types: 
      - completed
    branches:
      - main
  
jobs:
  release-advance-app:
    runs-on: windows-latest
    permissions:
      actions: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download Advance App Artifacts'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const packs = ["app-advance-windows"];
            const downloadPath = `${process.env.GITHUB_WORKSPACE}/`;
            const obj = await github.rest.actions.listWorkflowRunArtifacts({repo: context.repo.repo, owner: context.repo.owner, run_id: context.payload.workflow_run.id});
            for (var item of packs) 
            {
              console.log(item);
              const requiredPack = obj.data.artifacts.filter((pack) => { return pack.name == item } )[0];
              const getArtifacts = await github.rest.actions.downloadArtifact({ archive_format: 'zip', repo: context.repo.repo, artifact_id: requiredPack.id, owner: context.repo.owner });
              const filePath = downloadPath + item + '.zip';
              fs.writeFileSync(filePath, Buffer.from(getArtifacts.data));
            };

      - name: 'Unzip Advance App Artifacts'
        run: |
          unzip app-advance-windows.zip

      - name: 🟢 Install Node.js 18
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 18
          scope: '@naveed235812'
          registry-url: https://registry.npmjs.org

      - name: Publish Advance App
        run: |
          import os
          from glob import glob
          artifacts = glob('naveed235812-app-advance-windows*.tgz')
          for artifact in artifacts:
            os.system("npm publish --access public " + artifact)
        shell: python
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_APP}}
